language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn docs:build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: 210d0430be999a0a5cecce724d48a985e64d2094
  keep_history: true
  on:
    branch: master