language: node_js
node_js:
  - lts/*
install:
  - yarn install # npm ci
script:
  - yarn vuepress build # npm run docs:build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 6f97fbc53c0f68c9e56ae22d068870c693600a07
  keep_history: true
  on:
    branch: master